const Homeproduct =
[
    {
        id: 1,
        Name: 'Sony',
        price: '26',
        image: 'image/p1.webp',
        cat: 'tv',
        type: 'new',
    },
    {
        id: 2,
        Name: 'LG',
        price: '96',
        image: 'image/p2.webp',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 3,
        Name: 'Apple',
        price: '236',
        image: 'image/p3.webp',
        cat: 'watch',
        type: 'new',
    },
    {
        id: 4,
        Name: 'Lenovo',
        price: '636',
        image: 'image/p9.jpg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 5,
        Name: 'OnePlus',
        price: '98',
        image: 'image/p4.webp',
        cat: 'speaker',
        type: 'featured',
    },
    {
        id: 6,
        Name: 'LG',
        price: '59',
        image: 'image/p5.webp',
        cat: 'electronics',
        type: 'featured',
    },
    {
        id: 7,
        Name: 'Mivi',
        price: '956',
        image: 'image/p10.jpg',
        cat: 'headphone',
        type: 'featured',
    },
    {
        id: 8,
        Name: 'Panasonic',
        price: '389',
        image: 'image/p11.jpg',
        cat: 'electronics',
        type: 'featured',
    },
    {
        id: 9,
        Name: 'Oppo',
        price: '67',
        image: 'image/p6.webp',
        cat: 'phone',
        type: 'top',
    },
    {
        id: 10,
        Name: 'Sony',
        price: '76',
        image: 'image/p7.webp',
        cat: 'speaker',
        type: 'top',
    },
    {
        id: 11,
        Name: 'Apple',
        price: '87',
        image: 'image/p8.webp',
        cat: 'speaker',
        type: 'top',
    },
    {
        id: 12,
        Name: 'Samsung',
        price: '807',
        image: 'image/p12.jpg',
        cat: 'speaker',
        type: 'top',
    },
]
export default Homeproduct